packages:
  - packages/apps/*
  - packages/chief/*
  - packages/libs/*
  - packages/shared/*
  - packages/workers/*
  - packages/web
  - utils/*
onlyBuiltDependencies:
  - "@parcel/watcher"
  - electron
  - esbuild
  - sharp
  - workerd
