/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as HomeImport } from "./routes/home";
import { Route as ErrorImport } from "./routes/error";
import { Route as IndexImport } from "./routes/index";
import { Route as CreateScenarioImport } from "./routes/create/scenario";
import { Route as CreateFactionImport } from "./routes/create/faction";
import { Route as CreateCustomFactionImport } from "./routes/create/custom-faction";

// Create/Update Routes

const HomeRoute = HomeImport.update({
	id: "/home",
	path: "/home",
	getParentRoute: () => rootRoute,
} as any);

const ErrorRoute = ErrorImport.update({
	id: "/error",
	path: "/error",
	getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

const CreateScenarioRoute = CreateScenarioImport.update({
	id: "/create/scenario",
	path: "/create/scenario",
	getParentRoute: () => rootRoute,
} as any);

const CreateFactionRoute = CreateFactionImport.update({
	id: "/create/faction",
	path: "/create/faction",
	getParentRoute: () => rootRoute,
} as any);

const CreateCustomFactionRoute = CreateCustomFactionImport.update({
	id: "/create/custom-faction",
	path: "/create/custom-faction",
	getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		"/error": {
			id: "/error";
			path: "/error";
			fullPath: "/error";
			preLoaderRoute: typeof ErrorImport;
			parentRoute: typeof rootRoute;
		};
		"/home": {
			id: "/home";
			path: "/home";
			fullPath: "/home";
			preLoaderRoute: typeof HomeImport;
			parentRoute: typeof rootRoute;
		};
		"/create/custom-faction": {
			id: "/create/custom-faction";
			path: "/create/custom-faction";
			fullPath: "/create/custom-faction";
			preLoaderRoute: typeof CreateCustomFactionImport;
			parentRoute: typeof rootRoute;
		};
		"/create/faction": {
			id: "/create/faction";
			path: "/create/faction";
			fullPath: "/create/faction";
			preLoaderRoute: typeof CreateFactionImport;
			parentRoute: typeof rootRoute;
		};
		"/create/scenario": {
			id: "/create/scenario";
			path: "/create/scenario";
			fullPath: "/create/scenario";
			preLoaderRoute: typeof CreateScenarioImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/error": typeof ErrorRoute;
	"/home": typeof HomeRoute;
	"/create/custom-faction": typeof CreateCustomFactionRoute;
	"/create/faction": typeof CreateFactionRoute;
	"/create/scenario": typeof CreateScenarioRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/error": typeof ErrorRoute;
	"/home": typeof HomeRoute;
	"/create/custom-faction": typeof CreateCustomFactionRoute;
	"/create/faction": typeof CreateFactionRoute;
	"/create/scenario": typeof CreateScenarioRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexRoute;
	"/error": typeof ErrorRoute;
	"/home": typeof HomeRoute;
	"/create/custom-faction": typeof CreateCustomFactionRoute;
	"/create/faction": typeof CreateFactionRoute;
	"/create/scenario": typeof CreateScenarioRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/error" | "/home" | "/create/custom-faction" | "/create/faction" | "/create/scenario";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/error" | "/home" | "/create/custom-faction" | "/create/faction" | "/create/scenario";
	id: "__root__" | "/" | "/error" | "/home" | "/create/custom-faction" | "/create/faction" | "/create/scenario";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	ErrorRoute: typeof ErrorRoute;
	HomeRoute: typeof HomeRoute;
	CreateCustomFactionRoute: typeof CreateCustomFactionRoute;
	CreateFactionRoute: typeof CreateFactionRoute;
	CreateScenarioRoute: typeof CreateScenarioRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	ErrorRoute: ErrorRoute,
	HomeRoute: HomeRoute,
	CreateCustomFactionRoute: CreateCustomFactionRoute,
	CreateFactionRoute: CreateFactionRoute,
	CreateScenarioRoute: CreateScenarioRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/error",
        "/home",
        "/create/custom-faction",
        "/create/faction",
        "/create/scenario"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/create/custom-faction": {
      "filePath": "create/custom-faction.tsx"
    },
    "/create/faction": {
      "filePath": "create/faction.tsx"
    },
    "/create/scenario": {
      "filePath": "create/scenario.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
